[package]
name = "presto"
version = "0.1.0"
edition = "2024"

[dependencies]
cgmath = "0.18.0"
vulkano = "0.35.1"
vulkano-shaders = "0.35.0"
gltf = { version = "1.4.1", features = ["names"] }
glfw = { version = "*", default-features = false, features = [
  "vulkan",
  "x11",
  "raw-window-handle-v0-6",
] }
